#!/usr/bin/env bash
delredis () {
  echo "keys *" | redis-cli | cut -d' ' -f2 | while read line; do
    echo "Deleting $line";
    echo "del $line" | redis-cli;
  done
}
flatload () {
  cat $1 | while read line; do
    echo "loading $line into \e[0;32redis\e[0m"
    key="$(echo $line | cut -d'|' -f2)"
    value="$(echo $line | cut -d'|' -f3)"
    echo "set $key $value" | redis-cli
  done
}
delredis
flatload initial.flat
