#!/usr/bin/env bash

gensecp () {
  openssl ecparam -name secp384r1 -genkey -noout -out secp384r1.pem
  openssl ec -in secp384r1.pem -pubout -out secp384r1.pub
}

selfgen () {
  gensecp
  cp secp384r1.pem ca.key
  openssl req -new -x509 -key ./ca.key -out ./ca.crt -days 13653 -subj "/C=XX/ST=XX/L=XX/O=XX/OU=XX/CN=X1" &&
  gensecp
  cp secp384r1.pem inter.key
  openssl req -out CSR.csr -new -key secp384r1.pem -subj "/C=WW/ST=XX/L=XX/O=XX/OU=XX/CN=X2" &&
  openssl x509 -req -days 365 -in CSR.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out generated.pem -sha256
  openssl verify -CAfile ca.crt generated.pem || exit 1

}

selfgen

cat generated.pem secp384r1.pem > identity.pem
cat ca.crt >> auth.pem

openssl genrsa 4096 > sign.key
openssl rsa -in sign.key -pubout > sign.pub

mkdir hapid 2>/dev/null
cd hapid
pwd &&
selfgen
cat generated.pem secp384r1.pem > ../keycert.pem
cd ..
rm -rf hapid
